image: "rust:1.52.1"

before_script:
  - echo "Preparing run..."
  - mkdir -p /root/.ssh
  - chmod 700 /root/.ssh
  - touch /root/.ssh/known_hosts
  - chmod 600 /root/.ssh/known_hosts
  - ssh-keyscan -H github.com | tee -a /root/.ssh/known_hosts
  - apt update -y && apt install openssh-client -y
  - eval $(ssh-agent -s) 
  - echo "$GITHUB_OPENSSL_RS" | tr -d '\r' | ssh-add - > /dev/null
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - apt install -y clang

build:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --verbose

test:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --verbose

# Test that gathering coverage works
# todo, as this requires a rust nightly
#test-trace-pc-guard:
#  script:
#    - tools/coverage.sh

pages:
  script:
  - cargo doc
  - mv target/doc public
  artifacts:
    paths:
    - public
  only:
  - main

