image: "rust:1.51.0"

before_script:
  - echo "Preparing run..."
  - mkdir -p /root/.ssh
  - chmod 700 /root/.ssh
  - touch /root/.ssh/known_hosts
  - chmod 600 /root/.ssh/known_hosts
  - ssh-keyscan -H github.com | tee -a /root/.ssh/known_hosts
  - apt update -y && apt install openssh-client -y
  - eval $(ssh-agent -s) 
  - echo "$GITHUB_OPENSSL_RS" | tr -d '\r' | ssh-add - > /dev/null
  - git submodule sync --recursive
  - git submodule update --init --recursive


test:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

pages:
  script:
  - cargo doc
  - mv target/doc public
  artifacts:
    paths:
    - public
  only:
  - main

