image: "rust:1.52.1"

before_script:
  - echo "Preparing run..."
  - mkdir -p /root/.ssh
  - chmod 700 /root/.ssh
  - touch /root/.ssh/known_hosts
  - chmod 600 /root/.ssh/known_hosts
  - ssh-keyscan -H github.com | tee -a /root/.ssh/known_hosts
  - apt update -y && apt install openssh-client -y
  - eval $(ssh-agent -s) 
  - echo "$GITHUB_OPENSSL_RS" | tr -d '\r' | ssh-add - > /dev/null
  - git submodule sync --recursive
  - git submodule update --init --recursive
  # clang for compilation and xutils-dev for makedepend which is needed for OpenSSL 1.0.1
  - apt install -y clang xutils-dev
  - rustc --version && cargo --version  # Print version info for debugging

build-openssl111:
  script:
    - cargo test
    - cargo build --bin tlspuffin --verbose

build-libressl:
  script:
    - cargo build --bin tlspuffin --no-default-features --features="libressl sancov_libafl introspection" --verbose

pages:
  script:
  - cargo doc --lib --no-deps
  - mv target/x86_64-unknown-linux-gnu/doc public
  artifacts:
    paths:
    - public
  only:
  - main

