[package]
name = "tlspuffin"
version = "0.1.0"
authors = ["Maximilian Ammann <max@maxammann.org>"]
edition = "2018"
resolver = "2"

[features]
default = ["sancov_libafl", "ossl110", "introspection"]
# Logs each execution of __sanitizer_cov_trace_pc_guard*
sancov_pcguard_log = []
# Uses libafl for the instrumentation. sancov_pcguard_log and sancov_libafl are mutally exclusive
sancov_libafl = ["libafl_targets/sancov_pcguard_hitcounts", "libafl_targets/sancov_cmplog"]
# Uses OpenSSL 1.1.0 APIs
ossl110 =[]
# Uses only OpenSSL 1.0.1 APIs
ossl101 = []
# Uses a random scheduler instead of minimizer
no-minimizer = []
# Enables ASAN
asan = ["openssl/asan"]
introspection = ["libafl/introspection"]

[dependencies]
# TLS
# Custom work because:
#   * Message is cloneable
#   * Disabled logical checks during parsing of messages
#   * All modules exposed
rustls = { git = "https://github.com/maxammann/rustls.git", branch = "remove-checks" }
webpki = { version = "0.22.0", features = ["alloc", "std"] }
webpki-roots = "0.22.0"
ring = { version = "0.16", features = ["std"] }

# LibAFL
libafl = { git = "https://github.com/maxammann/LibAFL.git", branch = "fuzz" }
libafl_derive = { git = "https://github.com/maxammann/LibAFL.git", branch = "fuzz" }
libafl_targets = { git = "https://github.com/maxammann/LibAFL.git", branch = "fuzz" }

# Logging
log = "0.4"
log4rs = "1.0"

# TerminalStats
tui = "0.15"
nix = "0.21"
termion = "1.5"

# Utils
clap = "2"
hexdump = "*"
hex = "0.4"
rand = "0.8"
itertools = "0.10"
dyn-clone = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
postcard = { version = "0.7", features = ["alloc"] }
once_cell = "1.7"
chrono = "0.4"

# OpenSSL
# Uses build scripts from './openssl-src'
openssl = { path = "rust-openssl/openssl", features = ["vendored", "sancov", "no-rand"] }

[dev-dependencies]
criterion = "0.3"
# Support logging in tests
test-env-log = "0.2"
env_logger = "0.8" # Used for test-env-log
nix = "0.21"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[profile.dev]
panic = "abort"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name = "tlspuffin"
path = "src/main.rs"

# Used in tools/coverage.sh to generate coverage
[[example]]
name = "seed_successful"
