[package]
name = "crotofuzz"
version = "0.1.0"
authors = ["Maximilian Ammann <max@maxammann.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexdump = "0.1.1"
hex = "0.4.3"

log = "0.4.14"
pretty_env_logger = "0.4.0"
rand = "0.8.3"
rustls = "0.19.0"
webpki = "0.21.4"
webpki-roots = "0.21"

openssl = { version = "0.10.33", features = ["vendored"] }

[patch.crates-io]
openssl-src = { path = './openssl-src' }

[[bin]]
name = "simpleclient"
path = "src/simpleclient.rs"

[[bin]]
name = "crotofuzz"
path = "src/main.rs"

[[bin]]
name = "openssl_experiment"
path = "src/openssl_experiment.rs"
