[package]
name = "tlspuffin"
version = "0.1.0"
authors = ["Maximilian Ammann <max@maxammann.org>"]
edition = "2018"
resolver = "2"


[features]
default = ["sancov_pcguard_libafl"]
# Logs each execution of __sanitizer_cov_trace_pc_guard*
sancov_pcguard_log = []
# Uses libafl for the instrumentation. sancov_pcguard_log and sancov_pcguard_libafl are mutally exclusive
sancov_pcguard_libafl = ["libafl_targets/sancov_pcguard_hitcounts"]


[dependencies]
# TLS helpers
rustls = "0.19"
webpki = "0.21"
webpki-roots = "0.21"
ring = "0.16"

# LibAFL
libafl = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "1089c93" }
libafl_derive = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "1089c93" }
libafl_targets = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "1089c93" }

# Logging
log = "0.4"
env_logger = "0.8"
test-env-log = "0.2"

# Utils
hexdump = "0.1"
hex = "0.4"
rand = "0.8"
itertools = "0.10"
dyn-clone = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
postcard = { version = "0.7", features = ["alloc"] }

# OpenSSL
openssl = { version = "0.10.33", features = ["vendored"] }

[patch.crates-io]
openssl-src = { path = './openssl-src' }

[dev-dependencies]
criterion = "0.3"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[profile.dev]
panic = "abort"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name = "tlspuffin"
path = "src/main.rs"

[[bin]]
name = "tlspuffin_corpus"
path = "src/generate_corpus.rs"

# Used in tools/coverage.sh to generate coverage
[[example]]
name = "seed_successful"
