[workspace]

resolver = "2"

members = [
    "puffin",
    "tlspuffin",
    "sshpuffin",
    "tlspuffin-claims",
]

exclude = [ "deps/rust-libressl-src", "deps/rust-openssl-src", "deps/rust-openssl", "deps/rust-rustls", "deps/wolfssl-sys" ]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[profile.dev]
panic = "abort"
