[package]
name = "tlspuffin"
version = "0.1.0"
authors = ["Maximilian Ammann <max@maxammann.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexdump = "0.1.1"
hex = "0.4.3"
rand = "0.8.3"
itertools = "0.10.0"

dyn-clone = "1.0.4"

rustls = "0.19.1"
webpki = "0.21.4"
webpki-roots = "0.21"
ring = "0.16.11"
openssl = { version = "0.10.33", features = ["vendored"] }

libc = "0.2"
libafl = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "bfbaa7a" }
libafl_derive = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "bfbaa7a" }
libafl_targets = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "bfbaa7a", features = ["sancov_pcguard_hitcounts", "libfuzzer"] }

log = "0.4.14"
env_logger = "0.8.3"
test-env-log = "0.2.7"

[patch.crates-io]
openssl-src = { path = './openssl-src' }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false

[features]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
debug = true

[profile.dev]
#panic = "abort"

[[bin]]
name = "tlspuffin"
path = "src/main.rs"
