[package]
name = "crotofuzz"
version = "0.1.0"
authors = ["Maximilian Ammann <max@maxammann.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rustls = "0.19.0"
hexdump = "0.1.1"
hex = "0.4.3"