[package]
name = "sshpuffin"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
puffin = { path = "../puffin" }

log = "0.4"
thiserror = "1.0"

# libssh

russh-cryptovec = "0.7.0-beta.1"
russh-keys = "0.22.0-beta.3"
russh-libsodium = "0.3.0-beta.1"

bitflags = "1.2"
byteorder = "1.3"
digest = "0.10.3"
flate2 = {version = "1.0"}
generic-array = "0.14"
rand = "0.8"
sha2 = "0.10.2"

futures = "0.3"
tokio = {version = "1.17.0", features = ["io-util", "rt-multi-thread", "time", "net", "sync", "macros", "process"]}

[dev-dependencies]
env_logger = "0.9.0"

[build-dependencies]
cmake = "0.1.48"
bindgen = "0.60.1"
