name: Build

on:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        name: ["openssl111", "openssl101f", "openssl102u", "libressl", "wolfssl520"]
        include:
          - name: openssl111
            features: openssl111
          - name: openssl101f
            features: openssl101f,asan
            apt-dependencies: xutils-dev
          - name: openssl102u
            features: openssl102u
          - name: libressl
            features: libressl
          - name: wolfssl520
            features: wolfssl520
    name: Build "${{ matrix.features }}"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup
        uses: ./.github/actions/setup
      - name: APT Dependencies
        if: matrix.apt-dependencies
        shell: bash
        run: sudo apt-get install -y ${{ matrix.apt-dependencies }}
      - name: Build
        shell: bash
        run: just build tlspuffin x86_64-unknown-linux-gnu "${{ matrix.features }}"
      - name: Check
        shell: bash
        run: just check tlspuffin x86_64-unknown-linux-gnu "${{ matrix.features }}"
      - name: Test
        if: "!matrix.skip-tests"
        shell: bash
        run: just test tlspuffin x86_64-unknown-linux-gnu "${{ matrix.features }}"
      - uses: actions/upload-artifact@v2
        with:
          name: tlspuffin
          path: target/x86_64-unknown-linux-gnu/release/tlspuffin
