name: Build

on:
  workflow_call:
    inputs:
      features:
        required: true
        type: string

jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        shell: bash
        run: cargo build -p tlspuffin --features "${{ inputs.features }}"
      - name: Check
        shell: bash
        run: just check tlspuffin x86_64-unknown-linux-gnu
      - name: Test x86_64 linux
        shell: bash
        run: just test tlspuffin x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: tlspuffin
          path: target/x86_64-unknown-linux-gnu/debug/tlspuffin
