name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - trailofbits
      - evaluation-2022

jobs:
  run-check:
    uses: ./.github/workflows/run-checks.yml
  build-linux:
    uses: ./.github/workflows/build-linux.yml
