name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-openssl111:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: cargo build --bin tlspuffin --verbose
      - name: Run tests
        run: cargo test --verbose
  build-libressl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: cargo build --bin tlspuffin --no-default-features --features="libressl sancov_libafl introspection" --verbose
      - name: Run tests
        run: cargo test --verbose
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: cargo doc --lib --no-deps
      - name: Run tests
        run: mv target/x86_64-unknown-linux-gnu/doc public
      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
